#!/usr/bin/env bash

MODULES=(can can_dev can_raw vcan)
if [ "$#" -eq 0 ]; then
    INTERFACES=(vcan0 vcan1)
else
    INTERFACES=("$@")
fi

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

for module in ${MODULES[@]}; do
    modprobe ${module}
done

for interface in ${INTERFACES[@]}; do
    ip link add ${interface} type vcan
    ip link set ${interface} up
done

ip --details --stats link show type vcan
